job('seed_job') {
    description('Seed job generated by JCasC + Job DSL')

    scm {
        git {
            remote {
                url('https://github.com/abrahamNtd/jcasc-poc.git')
            }
            branch('*/main')
        }
    }

    steps {
        shell('echo Seed job is ready. Configure Job DSL scripts as needed.')
    }
}